### ISSUE TITLE
Some questions about blkio Cgroup

### ISSUE THREAD

**Issue by younaman** [mk-fg/cgroup-tools#1]
Hello everyone,I am a gree hand of Cgroup!About blkio Cgroup.I learned that the blkio Cgroup only controls the direct io of process.But,my question is that how the blkio Cgroup limit the iops of processes?How the blkio Cgroup caculate the iops of a process?How the blkio Cgroup collection the information about iops of processes?If I want to read the source code of blkio Cgroup and understand it,where is the location?I would be grateful if you could give me some suggestion!Thans a lot!

**Comment by mk-fg** [comment]
It's a subsystem in Linux kernel, which is of course open-source and relatively well-documented, in bundled Documentation dir, mailing list and patchwork patch history and discussion/review wrt every feature, as well as third-party docs at LWN and such great sources, all of which you can probably just google.

But just in case, here's a few links to some of the aforementioned stuff:
- https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v1/blkio-controller.html
- https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html#io
- https://github.com/torvalds/linux (look at io scheduler code there - CFQ, BFQ, etc)

Also, this is not an issue here, has little to do with this project, which is also deprecated anyway.
Please try to ask about such stuff in more appropriate places in the future, not by randomly filing an "issue" in a barely related or relevant project.
(e.g. Stack Exchange sites come to mind, though maybe at least do a basic google search first)
